### ISSUE TITLE
Want the Site to be responsive at different Screen Sizes.

### ISSUE THREAD

**Issue by Harsh-Singh-Rajput** [Harsh-Singh-Rajput/Notepad#10] opened 2022-10-02 08:31 UTC
You can made the the site responsive at different screen sizes like _min-width: 360px_, _min-width: 640px_, _min-width: 768px_, min-width: 1024px, min-width: 1280px etc.
- You are free to made the design as your imagination flies.
- **Multiple contributors** can create PRs but one of the best responsive designs will be selected from the Multiple PRs.

>  **Don't worry if your PR is not selected/merged there will be many more issues you can solve or create which is relevant to the repository. Learning and contributing is the key 😀. Happy Hacking....**

**Comment by RhyshaKachari** [comment] 2022-10-02 18:30
I want to work on this issue . Kindly assign this to me :)

**Comment by Harsh-Singh-Rajput** [comment] 2022-10-03 17:57
> I want to work on this issue . Kindly assign this to me :)

Ok

**Comment by RhyshaKachari** [comment] 2022-10-05 19:37
@Harsh-Singh-Rajput I am not able to solve this issue. I am unassigning myself. Please assign it to someone else.

**Comment by allenabraham777** [comment] 2022-10-12 04:27
@Harsh-Singh-Rajput as the issue is back to unsolved. May be I can take it up. You can assign it to me.

**Comment by Harsh-Singh-Rajput** [comment] 2022-10-14 16:21
> @Harsh-Singh-Rajput I am not able to solve this issue. I am unassigning myself. Please assign it to someone else.

ok no issues

**Comment by Harsh-Singh-Rajput** [comment] 2022-10-24 17:07
> Hello, Harsh! Great project! I would like to contribute, as well. Can you assign this issue to me?

@mhenrique94 yes sure,  go ahead

**Comment by mhenrique94** [comment] 2022-10-25 15:05
@Harsh-Singh-Rajput thank you! Some elements will be added and few of structure will me modifyed. I hope you enjoy it! I will PR soon. :)

**Comment by Harsh-Singh-Rajput** [comment] 2022-10-25 18:37
> @Harsh-Singh-Rajput thank you! Some elements will be added and few of structure will me modifyed. I hope you enjoy it! I will PR soon. :)

Happy to see your excitement and energy.😀
Waiting for it

**Comment by mhenrique94** [comment] 2022-10-26 01:50
hey! do you wanna validate before my PR? I made some structural changes:
https://mhenrique94.github.io/Harshpad/ (yep, you should give it your name lol)

**Comment by Harsh-Singh-Rajput** [comment] 2022-10-26 03:56
> hey! do you wanna validate before my PR? I made some structural changes: https://mhenrique94.github.io/Harshpad/ (yep, you should give it your name lol)

You can create a pr I will check it on my system.
No issues

**Closed** 2022-10-28 08:33 UTC
Labels: enhancement, help wanted, good first issue, hacktoberfest-accepted
